language: go
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x

sudo: required

services:
  - docker

before_script:
  - export PATH=$HOME/gopath/bin:$PATH

before_install:
  - go mod vendor || true
  - go get -t -d ./...
  - make install.tools

install: true

script:
  - env | grep TRAVIS_
  - make .gitvalidation
  - make lint
  - make check-license
  - make test
  - make docs
