language: go
go:
  - 1.7

sudo: required

services:
  - docker

before_script:
  - export PATH=$HOME/gopath/bin:$PATH

before_install:
  - docker pull vbatts/pandoc
  - make install.tools
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install
  - go get -t -d ./...
  - make schema-fs

install: true

script:
  - env | grep TRAVIS_
  - git diff --exit-code
  - make .gitvalidation
  - make lint
  - make check-license
  - make test
  - make docs
